name: Validate blog entries
on:
  pull_request:

defaults:
  run:
    working-directory: scripts

jobs:
  validate-blog-entries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0 # fetches all commits so we can check diffs
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
        with:
          deno-version: v1.x
      - name: Get changed markdown files
        id: changed-files
        working-directory: .
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.sha }}
        run: |
          FILES=$(git diff --name-only --diff-filter=AM "$BASE_SHA" "$HEAD_SHA" -- '*.md' | tr '\n' ' ')
          echo "files=$FILES" >> $GITHUB_OUTPUT
      - name: Validate blog entries are listed in _blog.yml
        if: steps.changed-files.outputs.files != ''
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.files }}
        run: deno run --allow-read ./validate-blog-entries.ts $CHANGED_FILES