name: YAML schema validator
on: 
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: scripts

permissions: {}

jobs:
  yaml-schema-validation:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: v1.x
      - run: deno run --allow-net --allow-read ./validate-yaml.ts