name: YAML schema validator
on: 
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: scripts

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - run: deno run --allow-net --allow-read ./validate-yaml.ts