name: YAML schema validator
on: 
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: scripts

permissions: {}

jobs:
  yaml-schema-validation:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
        with:
          deno-version: v1.x
      - run: deno run --allow-net --allow-read ./validate-yaml.ts